from .individual_evaluator import IndividualEvaluator
from .simple_individual_evaluator import SimpleIndividualEvaluator

from .population_evaluator import PopulationEvaluator
from .simple_population_evaluator import SimplePopulationEvaluator
