name: Update Documentation

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v4.1.5

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5.1.0
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install ghp-import pdoc
        python -m pip install -r docs/requirements.txt

    - name: Update documentation
      run: |
        jupyter-book build docs/
        ghp-import -n -p -f docs/_build/html

    - name: Update API
      run: |
        pdoc -d numpy -o docs/api ./eckity
