name: Generate API Docs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    

jobs:
  run_tests:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Run gendocs script
      run: |
         sudo apt install python3-pip
         pip install pdoc
         chmod +x ./gendocs.bat
         ./gendocs.bat
      shell: bash
