name: Scan Changed Files

on:
  pull_request:
    branches: [main]

jobs:
  scan-changed-files:
    runs-on: ubuntu-latest
    name: Scan Changed Files
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35

      - name: Scan for 'random' in changed files
        id: random-detector
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            if grep -q -i "random" "$file"; then
              echo "Found random in $file"
              echo "RANDOM_DETECTED=true" >> $GITHUB_OUTPUT
              break
            fi
          done

      - name: Comment PR
        if: ${{ steps.random-detector.outputs.RANDOM_DETECTED == 'true' }}
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            🚨 This PR contains the word 'random' in its changed files 🚨
            Before merging, please verify that algorithm's random generator is being used
