name: Scan Changed Files

on:
  pull_request:
    branches: [main]

jobs:
  scan-changed-files:
    runs-on: ubuntu-latest
    name: Scan Changed Files
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Scan for 'random' in changed files
        id: random-detector
        run: |
          git diff HEAD..origin/main | grep -i -n "random" > detections.txt
          if [ -s detections.txt ]; then
            cat detections.txt
            echo "RANDOM_DETECTED=true" >> $GITHUB_OUTPUT
          fi

      - name: Comment PR
        if: ${{ steps.random-detector.outputs.RANDOM_DETECTED == 'true' }}
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            🚨 This PR contains the word 'random' in its changed files 🚨
            Before merging, please verify that the algorithm's random generator is being used
