name: Random usage detector

on:
  pull_request:
    branches: [main, develop]

jobs:
  scan-changed-files:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    name: Scan Changed Files
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Scan for 'random' in changed files
        id: random-detector
        run: |
            # Run git diff between the latest commit and origin/main and filter for lines starting with + or -
            touch detections.txt
            git diff HEAD..origin/main | grep -i -E '^[+-].*random.*' > detections.txt

            # Check if detections.txt has any content
            if [ -s detections.txt ]; then
                cat detections.txt
                echo "RANDOM_DETECTED=true" >> $GITHUB_OUTPUT
            else
                echo "No 'random' found in changed lines"
            fi

      - name: Comment PR
        if: ${{ steps.random-detector.outputs.RANDOM_DETECTED == 'true' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Use GitHub API to create a comment on the PR
          PR_NUMBER=${{ github.event.pull_request.number }}
          COMMENT="🚨 This PR contains the word 'random' in its changed files 🚨
          Before merging, please verify that the algorithm's random generator is being used."
          GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          COMMENT_URL="https://api.github.com/repos/${{ github.repository }}/issues/${PR_NUMBER}/comments"
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{ github.repository }}/issues/${PR_NUMBER}/comments \
             -f "body=${COMMENT}"
