name: Run Examples

on: 
  push:
    # TODO change to [main, develop]
    branches: [ examples ]
  pull_request:
    # TODO change to [main, develop]
    branches: []
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v4.1.5
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5.1.0
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install scikit-learn --use-pep517
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

    - name: Find and run Python files in parallel
      run: |
        for file in $(find examples -type f -name "*.py"); do
          echo "Running $file"
          python "$file" 2>&1 | tee -a "$file.log"
          if grep -q "Error" "$file.log"; then
            echo "Error found in $file"
            exit 1
          fi
        done
