name: Check version changes

on:
  pull_request:
    branches:
      - main
      - "*" # This ensures it runs on PRs to any branch

jobs:
  check_version_change:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags

      # check that the version is updated on a PR to main
      # and not updated on a PR to other branches
      - name: Scan for '__version__' in changed files
        id: version-detector
        run: |
          TARGET_BRANCH="develop"
          BASE_SHA=$(git merge-base HEAD origin/$TARGET_BRANCH)

          # Check for version changes
          git diff $BASE_SHA..HEAD | grep -E -i -n '__version__\s*=\s*["\047][^\047"]+["\047]' > version_changes.txt

          if [ "$TARGET_BRANCH" == "main" ]; then
              if [ ! -s version_changes.txt ]; then
                  echo "ERROR: The version field was not changed in a pull request to main."
                  exit 1
              else
                  echo "There was no case in not changing version field in main."
              fi
          else
              if [ -s version_changes.txt ]; then
                  cat version_changes.txt
                  echo "ERROR: The version field should not be changed in pull requests to a branch that is not main."
                  exit 1
              else
                  echo "There was no case of changing version field in a non-main branch."
              fi
          fi

          echo "The __version__ line has been correctly handled for the '$TARGET_BRANCH' branch."
